### ISSUE TITLE
DOM Editing Lab

### ISSUE THREAD

**Issue by emilia-m26** [learn-co-curriculum/fewpjs-dom-editing-lab#7]
Hello, this lab has a slight confusion in reference to self-closing tags.  When you begin the lab, it is a blank page. It then asks to add is header element to the HTML file (<h1>My HTML adventure</h1>).  When this element is added, you are prompted to refresh the live page and check Elements tab, that a "new, self-closing child-node has appeared underneath body".  However, what would appear is the header tag, which is not self-closing.

Thanks!
Emilia

<img width="1056" alt="Screen Shot 2020-01-21 at 6 42 27 AM" src="https://user-images.githubusercontent.com/52939011/72802200-3ccae400-3c19-11ea-8634-0e5e31cc341f.png">

**Comment by sylwiavargas** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
