### ISSUE TITLE
Missing instructions for opening index.html file from WSL/Ubuntu

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/fewpjs-dom-editing-lab#9]
The instructions on this lab say to open the index.html file either with the `open index.html` command or `httpserver`. However, neither command works if you're using a WSL/Ubuntu environment. The correct command in that case is `explorer.exe index.html`.

I will fix this in a pull request.

--- Sdcrouse

**Comment by cernanb** [comment]
@Sdcrouse thanks for the PR!

**Comment by Sdcrouse** [comment]
No problem!
